name: Run tests on push / PR
on:
  push:
  pull_request:
jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest','windows-latest']
        version: ['5.1.2']
    runs-on: ${{ matrix.os }}
    steps:

    # - name: Checkout repository
    #   uses: actions/checkout@v4.1.1
    # # - name: Install bash 4(macOS)
    # #   if: runner.os == 'macOS'
    # #   run: brew install bash
    # # - name: Install blender (macOS)
    # #   if: runner.os == 'macOS'
    # #   run: brew install --cask blender

    - uses: actions/checkout@v5
    - name: Install Blender
      uses: bradyajohnston/setup-blender@v5
      with:
        version: ${{ matrix.version }}
    - name: Run tests in Blender
      run: blender --version

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b 

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run:  |
        uv run pytest --ignore=blender -vvv

    # - name: Run Advanced tests
    #   shell: bash
    #   run: |
    #     if [ "${{ runner.os }}" != "macOS" ]; then
    #       export BLENDER_BIN_PATH=${PWD}/blender/$(ls -AU blender | head -1)
    #       export PATH=$PATH:${BLENDER_BIN_PATH}
    #     fi
    #     cd fabex/tests
    #     uv run test_suite.py -vvv  

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blendercam-${{ matrix.os }}-${{ matrix.blender_version }}
        path: ./fabex
